name: custom_animated_splash
description: A customizable animated splash screen for Flutter apps using Lottie and native splash support.
version: 0.0.1
homepage: https://github.com/YusufFenni/custom_animated_splash
repository: https://github.com/YusufFenni/custom_animated_splash
issue_tracker: https://github.com/YusufFenni/custom_animated_splash/issues
documentation: https://github.com/YusufFenni/custom_animated_splash

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.3
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
